all:
  children:
    servicios:
      hosts:
        srv-01:
          ansible_host: 10.10.10.2
          device_name: "Radius"
          role: "Autenticación PPPoE"
        srv-02:
          ansible_host: 10.10.10.3
          device_name: "Ansible"
          role: "Automatización (Provisionamiento)"
        srv-03:
          ansible_host: 10.10.10.4
          device_name: "Zabbix"
          role: "Observabilidad (Monitoreo)"
        srv-04:
          ansible_host: 10.10.10.5
          device_name: "LibreQoS"
          role: "Calidad de Servicio (Shaping)"
        srv-05a:
          ansible_host: 10.10.10.6
          device_name: "DHCP"
          role: "Servicios básicos de red"
        srv-05b:
          ansible_host: 10.10.10.7
          device_name: "DNS"
          role: "Servicios básicos de red"
        srv-05c:
          ansible_host: 10.10.10.8
          device_name: "WEB"
          role: "Servicios básicos de red"
        srv-05d:
          ansible_host: 10.10.10.9
          device_name: "NTP"
          role: "Servicios básicos de red"
    core:
      hosts:
        rtr-edge-1:
          ansible_host: 10.10.20.1
          device_name: "RTR-EDGE-1"
          role: "BNG / PPPoE Server"
        cr-core-1:
          ansible_host: 10.10.20.2
          device_name: "CR-CORE-1"
          role: "Core Router Principal"
        cr-core-2:
          ansible_host: 10.10.20.3
          device_name: "CR-CORE-2"
          role: "Core Router Secundario"
    transporte:
      hosts:
        fw-edge-1:
          ansible_host: 10.10.30.1
          device_name: "FW-EDGE-1"
          role: "Firewall de Borde"
    distribuidores:
      hosts:
        sw-srv-1:
          ansible_host: 10.10.10.10
          device_name: "SW-SRV-1"
          role: "Switch de Agregación"
    olt:
      hosts:
        olt-acc-1:
          ansible_host: 10.10.40.10
          device_name: "OLT-ACC-1"
          role: "Acceso Fibra Óptica"
    radio:
      hosts:
        rad-01:
          ansible_host: 10.10.40.20
          device_name: "MIMOSA C5x"
          role: "Backhaul Inalámbrico"
        ap-acc-1:
          ansible_host: 10.10.40.30
          device_name: "AP-ACC-1"
          role: "Acceso Inalámbrico"
    ont:
      hosts: {}
